In [82]:
import pandas as pd

In [83]:
df = pd.read_csv("df_v3_30_nearest_average.csv",index_col=0)

In [84]:
df = df.dropna()

In [85]:
def ar_loyer(x):
    ar_loyer_m2 = {
    "1": 37.1, "2": 36.3, "3": 37.3, "4": 37, "5": 35.3, "6": 38.4,
    "7": 36.9, "8": 34.6, "9": 33.3, "10": 32.7, "11": 32.2, "12": 29.2,
    "13": 29, "14": 30.5, "15": 30.5, "16": 32.6, "17": 32.2, "18": 30.9,
    "19": 27.4, "20": 28
    }
    try:
        ar_loyer_m2[x]
    except:
        print(x)
    return ar_loyer_m2[x]

**on remplace l'arrondissement par le prix au m²**

In [86]:
df['District'] = df['District'].apply(lambda x :ar_loyer(str(x)))

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40042 entries, 0 to 40043
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   District                      40042 non-null  float64
 1   Accommodates                  40042 non-null  int64  
 2   Bathrooms                     40042 non-null  float64
 3   Bedrooms                      40042 non-null  float64
 4   Beds                          40042 non-null  float64
 5   Price                         40042 non-null  float64
 6   Security Deposit              40042 non-null  float64
 7   Cleaning Fee                  40042 non-null  float64
 8   Guests Included               40042 non-null  int64  
 9   Extra People                  40042 non-null  int64  
 10  Availability 60               40042 non-null  int64  
 11  Reviews per Month             40042 non-null  float64
 12  Calendar Updated (in days)    40042 non-null  int64  
 13  H

In [88]:
df.describe()

District  Accommodates     Bathrooms      Bedrooms          Beds  \
count  40042.000000  40042.000000  40042.000000  40042.000000  40042.000000   
mean      32.555989      3.058564      1.084736      1.040433      1.688377   
std        3.039803      1.498579      0.369185      0.792114      1.058863   
min       27.400000      1.000000      0.000000      0.000000      0.000000   
25%       30.500000      2.000000      1.000000      1.000000      1.000000   
50%       32.200000      2.000000      1.000000      1.000000      1.000000   
75%       35.300000      4.000000      1.000000      1.000000      2.000000   
max       38.400000     16.000000      8.000000     10.000000     16.000000   

              Price  Security Deposit  Cleaning Fee  Guests Included  \
count  40042.000000      40042.000000  40042.000000     40042.000000   
mean      92.894311        197.294466     24.002298         1.462315   
std       71.012599        212.816038     27.221128         0.943731   
min        8.000000          0.000000      0.000000         1.000000   
25%       54.000000          0.000000      0.000000         1.000000   
50%       75.000000        150.000000     20.000000         1.000000   
75%      102.000000        300.000000     38.000000         2.000000   
max      999.000000        999.000000    750.000000        16.000000   

       Extra People  ...  Type of Room      Real Bed  Cancellation_Policy  \
count  40042.000000  ...  40042.000000  40042.000000         40042.000000   
mean       6.218496  ...      2.858124      0.890490             2.106438   
std       13.073179  ...      0.374941      0.312282             0.814389   
min        0.000000  ...      1.000000      0.000000             1.000000   
25%        0.000000  ...      3.000000      1.000000             1.000000   
50%        0.000000  ...      3.000000      1.000000             2.000000   
75%       10.000000  ...      3.000000      1.000000             3.000000   
max      753.000000  ...      3.000000      1.000000             3.000000   

          Superhost  Host profile pic  Host ID verified  Instant bookable  \
count  40042.000000      40042.000000      40042.000000      40042.000000   
mean       0.074122          0.997603          0.602218          0.221143   
std        0.261973          0.048906          0.489446          0.415022   
min        0.000000          0.000000          0.000000          0.000000   
25%        0.000000          1.000000          0.000000          0.000000   
50%        0.000000          1.000000          1.000000          0.000000   
75%        0.000000          1.000000          1.000000          0.000000   
max        1.000000          1.000000          1.000000          1.000000   

                lat           lon    30 nearest  
count  40042.000000  40042.000000  40042.000000  
mean      48.863681      2.345512      0.409773  
std        0.017911      0.032146      0.069762  
min       48.816590      2.227926      0.183167  
25%       48.850966      2.325614      0.368350  
50%       48.864366      2.348556      0.412290  
75%       48.878083      2.368972      0.449755  
max       48.901013      2.421537      2.117988  

[8 rows x 28 columns]

# Preprocessing

> Les éléments utilisés dans la fonction objective d'un algorithme d'apprentissage (comme le noyau des machines à vecteurs de support ou les régularisateurs L1 et L2 des modèles linéaires) **supposent** que toutes les **entités sont centrées autour de zéro et ont une variance dans le même ordre**. Si une caractéristique a une variance de plusieurs ordres de grandeur plus grande que d'autres, elle pourrait dominer la fonction objective et empêcher l'estimateur d'apprendre correctement des autres caractéristiques comme prévu.

> Ici les variables quantitatives sont : 'Accommodates', 'Bathrooms', 'Bedrooms', 'Beds', 'Price',
       'Security Deposit', 'Cleaning Fee', 'Guests Included', 'Extra People',
       'Availability 60', 'Reviews per Month', 'Calendar Updated (in days)',
       'Host since (in days)', 'Number of Amenities',
       'Number of host verifications', 'Global review score', '30 nearest'


> Les variables catégoriels sont : 'District',
       'Type of property', 'Type of Room', 'Real Bed', 'Cancellation_Policy',
       'Superhost', 'Host profile pic', 'Host ID verified', 'Instant bookable',
       'lat', 'lon'

In [89]:
from sklearn import preprocessing
import numpy as np

In [90]:
X1_ = df[['District','Accommodates', 'Bathrooms', 'Bedrooms', 'Beds', 'Security Deposit', 
         'Cleaning Fee', 'Guests Included', 'Extra People', 'Availability 60', 'Reviews per Month', 
         'Calendar Updated (in days)', 'Host since (in days)', 'Number of Amenities', 
         'Number of host verifications', 'Global review score', '30 nearest']]

(**On ne prend pas pas lat lon**)

In [91]:
X2_ = df[['Type of property', 'Type of Room', 'Real Bed', 
         'Cancellation_Policy', 'Superhost', 'Host profile pic', 
         'Host ID verified', 'Instant bookable']]

In [92]:
Y_ = df['Price']

In [93]:
X1_.shape, X2_.shape, Y_.shape, df.shape # 17 + 8 + 1 = 28 - 2 OK 

((40042, 17), (40042, 8), (40042,), (40042, 28))

In [94]:
X1, Y, X2 = preprocessing.scale(X1_), preprocessing.scale(Y_), X2_.copy()

In [95]:
X = np.concatenate((X1,X2), axis=1)

In [96]:
X.shape, Y.shape

((40042, 25), (40042,))

In [97]:
X_ = X1_.join(X2_) # utile pour avoir le nom des colonnes de X

# 1 : Régression linéaire simple

In [98]:
from sklearn.model_selection import train_test_split

In [99]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

Les variables quantitative sont centrés-réduites, les variables catégorielles et issues d'un one-hot-enconding sont laissées tels quels

 ## Essayons un modèle de regression linéaire

In [100]:
from sklearn import linear_model

In [101]:
reg = linear_model.LinearRegression()

In [102]:
reg.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [103]:
len(reg.coef_[np.abs(reg.coef_) > 0.05])

13

In [104]:
np.abs(reg.coef_).argsort()[-14:]

array([15, 24, 10, 23, 13, 17,  9,  6, 21,  2,  0,  1,  3, 18],
      dtype=int64)

In [105]:
X_.columns[[10, 23, 13, 24, 22, 17,  9,  6, 21,  0,  2,  1,  3, 18]]

Index(['Reviews per Month', 'Host ID verified', 'Number of Amenities',
       'Instant bookable', 'Host profile pic', 'Type of property',
       'Availability 60', 'Cleaning Fee', 'Superhost', 'District', 'Bathrooms',
       'Accommodates', 'Bedrooms', 'Type of Room'],
      dtype='object')

Les colonnes suivantes sont les plus significatives par ordre croissant:
> 'Availability 60', 'Cleaning Fee', 'Superhost', 'District', 'Bathrooms',
       'Accommodates', 'Bedrooms', 'Type of Room'

In [132]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [107]:
Y_pred = reg.predict(X_test)

In [108]:
print(f'Mean squared error: {mean_squared_error(Y_test, Y_pred):.2f}')
# R²
print(f'Coefficient of determination: {r2_score(Y_test, Y_pred):.2f}')

Mean squared error: 0.39
Coefficient of determination: 0.62


## Regression Ridge + Lasso : Elastic Net

(repris et traduit de la doc scikit-learn)
> La régression Ridge résout certains des problèmes de la regression simple des moindres carrés ordinaires en imposant une pénalité à la taille des coefficients. Les coefficients de pénalité L2/Ridge minimisent une somme résiduelle de carrés pénalisée.

>La régression Lasso est un modèle linéaire qui estime des coefficient potentiellement non signficatif. Il est utile dans certains contextes en raison de sa tendance à préférer des solutions avec moins de coefficients non nuls, réduisant efficacement le nombre de caractéristiques dont dépend la solution donnée.

> Elastic Net est un mélange des deux : la fonction Objectif à minimiser devient :

 $$\min_{w} { \frac{1}{2n_{\text{samples}}} ||X w - y||_2 ^ 2 + \alpha \rho ||w||_1 +
\frac{\alpha(1-\rho)}{2} ||w||_2 ^ 2}$$

Pour determiner les meilleurs coefficient **alpha** et **rho** nous utiliserons des modèles de validations croisés 

In [109]:
from sklearn.linear_model import ElasticNetCV

In [110]:
reg_ENCV = ElasticNetCV()

In [111]:
reg_ENCV.fit(X_train, Y_train)

ElasticNetCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
             l1_ratio=0.5, max_iter=1000, n_alphas=100, n_jobs=None,
             normalize=False, positive=False, precompute='auto',
             random_state=None, selection='cyclic', tol=0.0001, verbose=0)

In [112]:
reg_ENCV.coef_

array([ 0.22571441,  0.23751875,  0.21800818,  0.23813015,  0.02390913,
       -0.00402532,  0.12454271, -0.00285919, -0.0065874 ,  0.11718191,
       -0.06240151, -0.01461285,  0.01313718,  0.06745317, -0.0261732 ,
        0.04804672,  0.00088909, -0.08665484,  0.25602767, -0.01748552,
        0.02769102,  0.12023944, -0.        ,  0.05775388,  0.05569504])

**la régression est moitié ridge/moitié lasso**

In [ ]:
reg_ENCV.

In [113]:
reg_ENCV.l1_ratio

0.5

In [114]:
reg_ENCV.alpha_

0.0012200477558212482

In [115]:
len(np.abs(reg_ENCV.coef_)[np.abs(reg_ENCV.coef_) > 0.1]) # nombre de coef > 0.1 en valeur absolue

8

In [116]:
np.abs(reg_ENCV.coef_).argsort()[-8:]

array([ 9, 21,  6,  2,  0,  1,  3, 18], dtype=int64)

In [117]:
reg_ENCV.coef_[[ 9, 21,  6,  0,  2,  1,  3, 18]]

array([0.11718191, 0.12023944, 0.12454271, 0.22571441, 0.21800818,
       0.23751875, 0.23813015, 0.25602767])

In [118]:
X_.columns[[ 9, 21,  6,  0,  2,  1,  3, 18]]

Index(['Availability 60', 'Superhost', 'Cleaning Fee', 'District', 'Bathrooms',
       'Accommodates', 'Bedrooms', 'Type of Room'],
      dtype='object')

Les colonnes suivantes les plus signficatives par ordre croissant :
> 'Availability 60', 'Superhost', 'Cleaning Fee', 'District', 'Bathrooms',
       'Accommodates', 'Bedrooms', 'Type of Room'

In [119]:
Y2_pred = reg_ENCV.predict(X_test)

In [134]:
print(f'Mean squared error: {mean_squared_error(reg_ENCV.predict(X_train), Y_train):.2f}')
# R²
print(f'Coefficient of determination: {r2_score(reg_ENCV.predict(X_train), Y_train):.2f}')

Mean squared error: 0.77
Coefficient of determination: -0.05


In [120]:
print(f'Mean squared error: {mean_squared_error(Y_test, Y2_pred):.2f}')
# R²
print(f'Coefficient of determination: {r2_score(Y_test, Y2_pred):.2f}')

Mean squared error: 0.39
Coefficient of determination: 0.62


# Réseau de Neurone

Comme les réseaux de neurone sont très sensible à l'ordre de grandeurs des valeurs, on normalise aussi les variables catégorielles

In [121]:
X2 = preprocessing.scale(X2_)

In [122]:
X = np.concatenate((X1,X2), axis=1)

In [123]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [124]:
from sklearn.neural_network import MLPRegressor

In [125]:
clf = MLPRegressor(hidden_layer_sizes=(30,30), verbose=True, max_iter=1000)

In [126]:
clf.fit(X_train, Y_train)

Iteration 1, loss = 0.24253733
Iteration 2, loss = 0.17989240
Iteration 3, loss = 0.16737889
Iteration 4, loss = 0.15993341
Iteration 5, loss = 0.15536963
Iteration 6, loss = 0.15199397
Iteration 7, loss = 0.14936066
Iteration 8, loss = 0.14620840
Iteration 9, loss = 0.14478924
Iteration 10, loss = 0.14337519
Iteration 11, loss = 0.14082081
Iteration 12, loss = 0.13990795
Iteration 13, loss = 0.13811208
Iteration 14, loss = 0.13657394
Iteration 15, loss = 0.13539382
Iteration 16, loss = 0.13466840
Iteration 17, loss = 0.13389187
Iteration 18, loss = 0.13301063
Iteration 19, loss = 0.13281148
Iteration 20, loss = 0.13099742
Iteration 21, loss = 0.13038223
Iteration 22, loss = 0.12947725
Iteration 23, loss = 0.12860046
Iteration 24, loss = 0.12789367
Iteration 25, loss = 0.12822164
Iteration 26, loss = 0.12677443
Iteration 27, loss = 0.12840031
Iteration 28, loss = 0.12621076
Iteration 29, loss = 0.12490004
Iteration 30, loss = 0.12533274
Iteration 31, loss = 0.12517267
Iteration 32, los

Iteration 252, loss = 0.09601423
Iteration 253, loss = 0.09562769
Iteration 254, loss = 0.09596035
Iteration 255, loss = 0.09563509
Iteration 256, loss = 0.09595721
Iteration 257, loss = 0.09551455
Iteration 258, loss = 0.09670041
Iteration 259, loss = 0.09556917
Iteration 260, loss = 0.09647499
Iteration 261, loss = 0.09596606
Iteration 262, loss = 0.09568483
Iteration 263, loss = 0.09549159
Iteration 264, loss = 0.09548804
Iteration 265, loss = 0.09605079
Iteration 266, loss = 0.09547925
Iteration 267, loss = 0.09561936
Iteration 268, loss = 0.09604062
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.


MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(30, 30), learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=1000,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=None, shuffle=True, solver='adam',
             tol=0.0001, validation_fraction=0.1, verbose=True,
             warm_start=False)

In [127]:
Y_pred = clf.predict(X_test)

In [128]:
print(f'Mean squared error: {mean_squared_error(Y_test, Y_pred):.2f}')
# R²
print(f'Coefficient of determination: {r2_score(Y_test, Y_pred):.2f}')

Mean squared error: 0.33
Coefficient of determination: 0.64


In [129]:
clf2 = MLPRegressor(hidden_layer_sizes=(50,40,30), verbose=True, max_iter=1000)

In [130]:
clf2.fit(X_train, Y_train)

Iteration 1, loss = 0.21234889
Iteration 2, loss = 0.16886611
Iteration 3, loss = 0.15965096
Iteration 4, loss = 0.15380971
Iteration 5, loss = 0.15099564
Iteration 6, loss = 0.14682978
Iteration 7, loss = 0.14412873
Iteration 8, loss = 0.14048138
Iteration 9, loss = 0.13872143
Iteration 10, loss = 0.13591878
Iteration 11, loss = 0.13493099
Iteration 12, loss = 0.13262910
Iteration 13, loss = 0.13177401
Iteration 14, loss = 0.12947549
Iteration 15, loss = 0.12792477
Iteration 16, loss = 0.12545935
Iteration 17, loss = 0.12608739
Iteration 18, loss = 0.12321689
Iteration 19, loss = 0.12284346
Iteration 20, loss = 0.12158540
Iteration 21, loss = 0.12042322
Iteration 22, loss = 0.11887379
Iteration 23, loss = 0.11871358
Iteration 24, loss = 0.11765222
Iteration 25, loss = 0.11551919
Iteration 26, loss = 0.11416198
Iteration 27, loss = 0.11497245
Iteration 28, loss = 0.11288979
Iteration 29, loss = 0.11100076
Iteration 30, loss = 0.11005133
Iteration 31, loss = 0.10889051
Iteration 32, los

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(50, 40, 30), learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=1000,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=None, shuffle=True, solver='adam',
             tol=0.0001, validation_fraction=0.1, verbose=True,
             warm_start=False)

In [133]:
Y_pred = clf.predict(X_test)
print(f'Mean squared error: {mean_squared_error(Y_test, Y_pred):.2f}')
# R²
print(f'Coefficient of determination: {r2_score(Y_test, Y_pred):.2f}')
print(f'Mean absolute error: {mean_absolute_error(Y_test, Y_pred):.2f}')


Mean squared error: 0.33
Coefficient of determination: 0.64
Mean absolute error: 0.33
